#!/usr/bin/env node

var exec = require('child_process').exec;
var cwd = process.cwd();

console.log('Running post-merge `npm install`...');

exec('npm install', function(err, stdout, stderr) {
  if (err) {
    console.log('commands: ' + fail);
    console.log(stdout);
    console.log(stderr);
    process.exit(1);
  } else {
    console.log('npm install successfully completed.')
    process.exit(0);
  }
});
