#!/usr/bin/env node
var exec = require('child_process').exec;
var cwd = process.cwd();

exec('npm install', { cwd: path }, function (err, stdout, stderr) {
    if (err) {
        console.log('commands: ' + fail);
        console.log(stdout);
        console.log(stderr);
        process.exit(1);
    } else {
        process.exit(0);
    }
});

console.log('running post-merge npm install...');
